name: Flutter CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
  release:
    types: [published]
  # For APK release on tag
  push:
    tags:
      - 'v*.*.*'

jobs:
  analyze-test:
    name: Analyze, Unit & Integration Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run unit tests
        run: flutter test
      - name: Run integration tests
        run: |
          if [ -d integration_test ]; then
            flutter test integration_test
          else
            echo "No integration_test/ directory found. Skipping integration tests."
          fi
      - name: Run code coverage
        run: flutter test --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  build-apk:
    name: Build & Release APK
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mangamari-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
